export const preconfigs = [
  require('./golden-seeds.json'),
  require('./unknown-pleasures.json'),
  require('./tree.json'),
  require('./dandelion.json'),
  require('./voronoi.json'),
  require('./color-sunflower.json'),
  require('./sponge.json'),
  require('./seashell.json'),
  require('./turbine.json'),
  require('./golden-circles.json'),
  require('./hinge-third.json'),
  require('./christmas-tree.json'),
  require('./overlapping-triangles.json'),
];
