export const preconfigs = [
  require('./golden-seeds.json'),
  // require('./spiral.json'),
  // require('./golden-spiral.json'),
  // require('./test.json'),
  // require('./test-voronoi.json'),
  require('./turbine.json'),
  require('./unknown-pleasures.json'),
  require('./cos_sin.json'),
  require('./voronoi.json'),
  require('./tree.json'),
  require('./dandelion.json'),
  require('./color-sunflower.json'),
  require('./sponge.json'),
  require('./seashell.json'),
  require('./golden-circles.json'),
  require('./hinge-third.json'),
  require('./christmas-cutout.json'),
];
